### ISSUE TITLE
Second node will not start: java.lang.VerifyError: Uninitialized object exists on backward branch

### ISSUE THREAD

**Issue by jmarchesini** [pablosmedina/kvstore#4]
Windows 8.1

java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

sbt launcher version 0.13.7

Member 1 comes up and becomes Leader:

==========================

C:\dev\kvstore>sbt -Dckite.finagle.listen-address=localhost:9091 -Dckite.datadir=c:\dev\data\ckite\member1 -Dckite.bootstrap=true
[info] Loading project definition from C:\dev\kvstore\project
[info] Set current project to kvstore (in build file:/C:/dev/kvstore/)
> run

[info] Running ckite.kvstore.KVStoreBootstrap
10:59:40,704 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:59:40,704 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:59:40,704 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/C:/dev/kvstore/targe
t/scala-2.11/classes/logback.xml]
10:59:40,754 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:59:40,758 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:59:40,764 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:59:40,775 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.PatternLayout] for [layout] property
10:59:40,801 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
10:59:40,801 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
10:59:40,801 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
10:59:40,802 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
10:59:40,804 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC]
10:59:40,804 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to ch.qos.logback.classic.AsyncAppender[ASYNC]
10:59:40,804 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Attaching appender named [STDOUT] to AsyncAppender.
10:59:40,804 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Setting discardingThreshold to 51
10:59:40,805 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ckite] to DEBUG
10:59:40,805 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
10:59:40,805 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:59:40,805 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:59:40,805 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@60944fda - Registering current configuration as safe fallback point

Aug 19, 2015 10:59:41 AM com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
INFO: Finagle version 6.27.0 (rev=65df1512aadc8b79871a6dcafbbd210fd088b055) built at 20150727-172532
10:59:41.276 INFO  [run-main-0] ckite.Raft - Starting CKite localhost:9091...
10:59:41.278 INFO  [run-main-0] ckite.RLog - Initializing RLog...
10:59:41.280 INFO  [run-main-0] ckite.RLog - No Snapshot was found
10:59:41.281 INFO  [run-main-0] ckite.RLog - No entry to replay. commitIndex is #0
10:59:41.284 INFO  [run-main-0] ckite.RLog - Done initializing RLog
10:59:41.286 INFO  [run-main-0] ckite.Raft - Bootstrapping a new CKite consensus cluster...
10:59:41.287 INFO  [Log-worker-1] ckite.RLog - Starting Log from index #0
10:59:41.290 INFO  [run-main-0] ckite.Membership - Cluster Configuration changed to SingleClusterConfiguration(Set(localhost:9091),1)
10:59:41.307 DEBUG [run-main-0] ckite.Consensus - Transition from Starter to Follower[0]
10:59:41.309 INFO  [run-main-0] ckite.LeaderAnnouncer - Waiting for a Leader to be announced...
10:59:43.160 DEBUG [ElectionTimeout-worker-1] ckite.states.ElectionTimeout - Timeout reached! Time to elect a new leader
10:59:43.161 DEBUG [ElectionTimeout-worker-1] ckite.Consensus - Transition from Follower[0] to Candidate[1]
10:59:43.161 DEBUG [ElectionTimeout-worker-1] ckite.states.Candidate - Start election
10:59:43.166 DEBUG [CandidateElection-worker-localhost:9091-1] ckite.states.Candidate - Got 1 votes
10:59:43.167 INFO  [CandidateElection-worker-localhost:9091-1] ckite.states.Candidate - Won the election. Will become Leader...
10:59:43.171 DEBUG [CandidateElection-worker-localhost:9091-1] ckite.Consensus - Transition from Candidate[1] to Leader[1]
10:59:43.172 DEBUG [CandidateElection-worker-localhost:9091-1] ckite.states.Leader - Start broadcasting...
10:59:43.175 INFO  [CandidateElection-worker-localhost:9091-1] ckite.states.Leader - Log is empty. First Leader. Appending initial cluster configuration
10:59:43.181 DEBUG [Log-worker-1] ckite.RLog - Appending LogEntry(term=1,index=1,NewConfiguration(Set(localhost:9091)))
10:59:43.191 DEBUG [ForkJoinPool-1-worker-13] ckite.states.Leader - No member to broadcast
10:59:43.193 DEBUG [Log-worker-1] ckite.RLog - New commitIndex is #1
10:59:43.193 DEBUG [Log-worker-1] ckite.RLog - Will apply committed entry LogEntry(term=1,index=1,NewConfiguration(Set(localhost:9091)))
10:59:43.195 DEBUG [Log-worker-1] ckite.RLog - Last applied index is #1
10:59:43.198 INFO  [ForkJoinPool-1-worker-13] ckite.states.Leader - Start being Leader[1]

==========================

So, I start member 2:

===========================

C:\dev\kvstore>sbt -Dckite.finagle.listen-address=localhost:9092 -Dckite.datadir=c:\dev\data\ckite\member2 -Dckite.members.0=localhost:9091
[info] Loading project definition from C:\dev\kvstore\project
[info] Set current project to kvstore (in build file:/C:/dev/kvstore/)
> run
[info] Running ckite.kvstore.KVStoreBootstrap
11:04:14,750 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:04:14,751 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:04:14,751 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/C:/dev/kvstore/target/scala-2.11/classes/logback.xml]
11:04:14,798 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:04:14,802 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:04:14,808 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:04:14,819 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.PatternLayout] for [layout] property
11:04:14,844 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:04:14,844 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:04:14,844 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:04:14,844 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
11:04:14,846 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC]
11:04:14,846 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to ch.qos.logback.classic.AsyncAppender[ASYNC]
11:04:14,846 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Attaching appender named [STDOUT] to AsyncAppender.
11:04:14,846 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Setting discardingThreshold to 51
11:04:14,847 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [ckite] to DEBUG
11:04:14,847 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
11:04:14,847 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:04:14,847 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:04:14,847 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@50fd961e - Registering current configuration as safe fallback point

11:04:14.925 DEBUG [run-main-0] ckite.RemoteMember - Creating RemoteMember client for localhost:9091
Aug 19, 2015 11:04:15 AM com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
INFO: Finagle version 6.27.0 (rev=65df1512aadc8b79871a6dcafbbd210fd088b055) built at 20150727-172532
11:04:15.514 INFO  [run-main-0] ckite.Raft - Starting CKite localhost:9092...
11:04:15.515 INFO  [run-main-0] ckite.RLog - Initializing RLog...
11:04:15.517 INFO  [run-main-0] ckite.RLog - No Snapshot was found
11:04:15.517 INFO  [run-main-0] ckite.RLog - No entry to replay. commitIndex is #0
11:04:15.519 INFO  [run-main-0] ckite.RLog - Done initializing RLog
11:04:15.519 INFO  [run-main-0] ckite.Raft - CKite not initialized. Join start
11:04:15.520 INFO  [run-main-0] ckite.Consensus - Start as Joiner. Using seeds: Set(localhost:9091)
11:04:15.520 INFO  [Log-worker-1] ckite.RLog - Starting Log from index #0
11:04:15.533 DEBUG [run-main-0] ckite.Consensus - Transition from Starter to Joiner[0]
11:04:15.534 INFO  [run-main-0] ckite.Consensus - Try to join with localhost:9091
11:04:15.535 DEBUG [run-main-0] ckite.RemoteMember - Joining with localhost:9091
[error] (run-main-0) java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [3 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:190)
        at ckite.Consensus$$anonfun$startAsJoiner$1$$anonfun$apply$mcV$sp$1.apply(Consensus.scala:49)
        at ckite.Consensus$$anonfun$startAsJoiner$1$$anonfun$apply$mcV$sp$1.apply(Consensus.scala:46)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
        at ckite.Consensus$$anonfun$startAsJoiner$1.apply$mcV$sp(Consensus.scala:46)
        at scala.util.control.Breaks.breakable(Breaks.scala:38)
        at ckite.Consensus.startAsJoiner(Consensus.scala:45)
        at ckite.Raft.joinStart(Raft.scala:33)
        at ckite.Raft.start(Raft.scala:23)
        at ckite.CKiteClient.start(CKiteClient.scala:35)
        at ckite.kvstore.KVStoreBootstrap$.delayedEndpoint$ckite$kvstore$KVStoreBootstrap$1(KVStoreBootstrap.scala:9)
        at ckite.kvstore.KVStoreBootstrap$delayedInit$body.apply(KVStoreBootstrap.scala:7)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at ckite.kvstore.KVStoreBootstrap$.main(KVStoreBootstrap.scala:7)
        at ckite.kvstore.KVStoreBootstrap.main(KVStoreBootstrap.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:run for the full output.

=============================================

Member 1 has what looks like a verification error with Thrift:

11:04:15.720 INFO  [finagle/netty3-1] ckite.Raft - Join member localhost:9092 request received
11:04:15.722 DEBUG [Log-worker-1] ckite.RLog - Appending LogEntry(term=1,index=2,JointConfiguration(Set(localhost:9091),Set(localhost:9091, localhost:9092)))
11:04:15.727 DEBUG [ForkJoinPool-1-worker-11] ckite.RemoteMember - Creating RemoteMember client for localhost:9092
11:04:15.855 INFO  [ForkJoinPool-1-worker-11] ckite.Membership - Cluster Configuration changed to JointClusterConfiguration(cold=Set(localhost:9091), cnew=Set(localhost:9091, localhost:9092), index= 2)
java.lang.VerifyError: Uninitialized object exists on backward branch 423
Exception Details:
  Location:
    ckite/rpc/thrift/AppendEntriesST$.lazyDecode(Lcom/twitter/scrooge/LazyTProtocol;)Lckite/rpc/thrift/AppendEntriesST; @453: goto

  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 0336 2603 3627 0236 2003 3621 1401 1237
    0000010: 1c14 0112 3717 0236 13b2 0047 3a0f 013a
    0000020: 0503 3e2b b901 1801 003d 2bc0 011a b601
    0000030: 1d57 1d99 0062 2bc0 011a b601 2015 2799
    0000040: 004b 1521 9900 3bbb 0122 592b 2bb9 0126
    0000050: 0100 1c2b b901 1801 0015 2615 2016 1c16
    0000060: 1715 1319 0f19 05c7 000a 2ab7 0128 a700
    0000070: 0d19 05b9 012d 0100 c000 b4b7 0130 b0bb
    0000080: 00be 5913 0132 b700 c3bf bb00 be59 1301
    0000090: 34b7 00c3 bf2b c001 1ab6 0137 3a22 1922
    00000a0: b401 3c03 a000 0804 3ea7 ff89 1922 b401
    00000b0: 4036 0415 04aa 0000 0000 0027 0000 0001
    00000c0: 0000 0006 0000 02a6 0000 0244 0000 01e4
    00000d0: 0000 0184 0000 0125 0000 006c 1905 c700
    00000e0: 0bb2 004c b601 443a 0519 05b2 0149 b200
    00000f0: 3a19 22b4 0140 b801 4fb6 0153 b201 5819
    0000100: 222b c001 1ab6 015c 3a08 3a07 3a06 bb01
    0000110: 5e59 1907 1908 b701 61b9 0165 0200 a702
    0000120: 9f19 22b4 013c 360a 150a aa00 0000 0012
    0000130: 0000 000f 0000 000f 0000 0048 bb00 be59
    0000140: bb01 6759 b200 3a3a 0913 0169 b701 6ab2
    0000150: 003a 05bd 016c 5903 2a10 0fb6 0170 5359
    0000160: 042a 150a b601 7053 b601 74b6 0178 b700
    0000170: c3bf bb00 6959 2bc0 011a 593a 0db6 017c
    0000180: 3a0b 190b b401 8103 a000 0e19 0db6 0184
    0000190: b201 89a7 003c bb01 8b59 190b b401 81b7
    00001a0: 018e 3a0e 0336 0c15 0c19 0bb4 0181 a200
    00001b0: 1a19 0eb2 0193 190d b601 97b6 019a 5715
    00001c0: 0c04 6036 0ca7 ffe2 190d b601 8419 0eb7
    00001d0: 0077 3a0f b200 89a7 01e6 1922 b401 3c36
    00001e0: 1115 11aa 0000 0011 0000 0008 0000 0008
    00001f0: 0000 0047 bb00 be59 bb01 6759 b200 3a3a
    0000200: 1013 019c b701 6ab2 003a 05bd 016c 5903
    0000210: 2a10 08b6 0170 5359 042a 1511 b601 7053
    0000220: b601 74b6 0178 b700 c3bf 2bc0 011a b601
    0000230: 9f36 13b2 0089 a701 8719 22b4 013c 3615
    0000240: 1515 aa00 0000 0012 0000 000a 0000 000a
    0000250: 0000 0048 bb00 be59 bb01 6759 b200 3a3a
    0000260: 1413 01a1 b701 6ab2 003a 05bd 016c 5903
    0000270: 2a10 0ab6 0170 5359 042a 1515 b601 7053
    0000280: b601 74b6 0178 b700 c3bf 2bc0 011a b601
    0000290: a437 17b2 0089 a701 2719 22b4 013c 361a
    00002a0: 151a aa00 0000 0012 0000 000a 0000 000a
    00002b0: 0000 0048 bb00 be59 bb01 6759 b200 3a3a
    00002c0: 1913 01a6 b701 6ab2 003a 05bd 016c 5903
    00002d0: 2a10 0ab6 0170 5359 042a 151a b601 7053
    00002e0: b601 74b6 0178 b700 c3bf 2bc0 011a b601
    00002f0: a437 1cb2 0089 a700 c719 22b4 013c 361f
    0000300: 151f aa00 0000 0012 0000 000b 0000 000b
    0000310: 0000 0048 bb00 be59 bb01 6759 b200 3a3a
    0000320: 1e13 01a8 b701 6ab2 003a 05bd 016c 5903
    0000330: 2a10 0bb6 0170 5359 042a 151f b601 7053
    0000340: b601 74b6 0178 b700 c3bf 2bb9 01ab 0100
    0000350: 3620 0436 21b2 0089 a700 6519 22b4 013c
    0000360: 3624 1524 aa00 0000 0000 0014 0000 0008
    0000370: 0000 0008 0000 004a bb00 be59 bb01 6759
    0000380: b200 3a3a 2313 01ad b701 6ab2 003a 05bd
    0000390: 016c 5903 2a10 08b6 0170 5359 042a 1524
    00003a0: b601 7053 b601 74b6 0178 b700 c3bf 2bc0
    00003b0: 011a b601 9f36 2604 3627 b200 8957 2bc0
    00003c0: 011a b601 b0a7 fc6d
  Stackmap Table:
    full_frame(@50,{Object[#2],Object[#277],Integer,Integer,Top,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224],Top,
Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Top,Top,Top,Top,Integer,Integer},{})
    full_frame(@113,{Object[#2],Object[#277],Integer,Integer,Top,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224],Top
,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Top,Top,Top,Top,Integer,Integer},{Uninitialized[#71],Un
initialized[#71],Object[#277],Object[#450],Integer,Integer,Integer,Integer,Long,Long,Integer,Object[#224]})
    full_frame(@123,{Object[#2],Object[#277],Integer,Integer,Top,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224],Top
,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Top,Top,Top,Top,Integer,Integer},{Uninitialized[#71],Un
initialized[#71],Object[#277],Object[#450],Integer,Integer,Integer,Integer,Long,Long,Integer,Object[#224],Object[#180]})
    same_frame(@127)
    same_frame(@138)
    same_frame(@149)
    full_frame(@172,{Object[#2],Object[#277],Integer,Integer,Top,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224],Top
,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    full_frame(@220,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    same_frame(@233)
    same_frame(@289)
    full_frame(@316,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Integer,Top,Top,Top,Top,Object[#
224],Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    same_frame(@370)
    full_frame(@406,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Integer,Object[#382],Top,Object[
#282],Top,Object[#224],Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Inte
ger,Integer},{Uninitialized[#370],Uninitialized[#370]})
    full_frame(@423,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Integer,Object[#382],Integer,Obj
ect[#282],Object[#395],Object[#224],Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top
,Top,Top,Integer,Integer},{Uninitialized[#370],Uninitialized[#370]})
    full_frame(@456,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Integer,Object[#382],Integer,Obj
ect[#282],Object[#395],Object[#224],Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top
,Top,Top,Integer,Integer},{Uninitialized[#370],Uninitialized[#370]})
    full_frame(@463,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Integer,Object[#382],Top,Object[
#282],Top,Object[#224],Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Inte
ger,Integer},{Uninitialized[#370],Uninitialized[#370],Object[#452]})
    full_frame(@474,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    full_frame(@500,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Integer,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    same_frame(@554)
    full_frame(@569,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    full_frame(@596,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Integer,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    same_frame(@650)
    full_frame(@665,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    full_frame(@692,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Integer,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    same_frame(@746)
    full_frame(@761,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    full_frame(@788,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Integer,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    same_frame(@842)
    full_frame(@859,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{})
    full_frame(@888,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Integer,Top,Integer,Integer},{})
    same_frame(@942)
    full_frame(@957,{Object[#2],Object[#277],Integer,Integer,Integer,Object[#298],Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#224]
,Top,Top,Top,Integer,Top,Top,Top,Long,Top,Top,Top,Long,Top,Top,Integer,Integer,Object[#313],Top,Top,Top,Integer,Integer},{Object[#
364]})

        at ckite.rpc.thrift.ThriftConverters$.appendEntriesToThrift(ThriftConverters.scala:22)
        at ckite.rpc.thrift.FinagleThriftClient.send(FinagleThriftClient.scala:32)
        at ckite.RemoteMember.sendAppendEntries(RemoteMember.scala:30)
        at ckite.states.Leader.ckite$states$Leader$$sendAppendEntries(Leader.scala:62)
        at ckite.states.Leader$$anonfun$ckite$states$Leader$$broadcast$1.apply(Leader.scala:54)
        at ckite.states.Leader$$anonfun$ckite$states$Leader$$broadcast$1.apply(Leader.scala:54)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at ckite.states.Leader.ckite$states$Leader$$broadcast(Leader.scala:54)
        at ckite.states.Leader.ckite$states$Leader$$broadcast(Leader.scala:170)
        at ckite.states.Leader$$anonfun$onWriteCommand$1.apply(Leader.scala:163)
        at ckite.states.Leader$$anonfun$onWriteCommand$1.apply(Leader.scala:160)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by pablosmedina** [comment]
Hi @jmarchesini,

CKite 0.2.0 was compiled with Java 8. I will specify that more clearly. Could you please try with a java 8 vm?

Thanks!

Pablo

**Comment by jmarchesini** [comment]
Hi Pablo -

Thanks for the quick reply!

The ckite README is stale:

"Implementation details

Built in Scala 2.11.7 and JDK 7."

Will upgrade to JDK 8 and re-test.

**Comment by pablosmedina** [comment]
Ok, please. Thanks for noticing that README is stale. I'll fix it.

**Comment by jmarchesini** [comment]
Upgraded to:

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Issue resolved.

Thank you.

**Comment by pablosmedina** [comment]
Great, thanks!
